chore: add a fail

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -94,11 +94,18 @@ jobs:
         id: labels-typical
         run: |
           ver=$(skopeo inspect docker://quay.io/${{ env.SOURCE_ORG }}/${{ env.SOURCE_IMAGE }}:${{ matrix.major_version }} | jq -r '.Labels["org.opencontainers.image.version"]')
-          echo "VERSION=$ver" >> $GITHUB_OUTPUT
+          echo "VERSION_TYP=$ver" >> $GITHUB_OUTPUT
+
+      - name: Get current version - fail
+        id: labels-fail
+        run: |
+          ver=$(skopeo inspect docker://quay.io/${{ env.SOURCE_ORG }}/${{ env.SOURCE_IMAGE }}:${{ matrix.major_version }} | jq -r '.Labels["org.opencontainers.image.version"]' && exit 1)
+          echo "VERSION_FAIL=$ver" >> $GITHUB_OUTPUT
 
       - name: Echo outputs
         run: |
           echo "${{ toJSON(steps.labels-typical.outputs) }}"
+          echo "${{ toJSON(steps.labels-fail.outputs) }}"
 
   check:
     name: Check all builds successful
